[project]
name = "ai-image-detector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "opencv-python>=4.8.1.78",
    "streamlit>=1.45.1",
    "tensorflow==2.13.0",
]
